# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
#  secret_key_base: 9a4da85c4ea0791173e75a0b800adcfdc9e71ba073669349a875dcc2ceb49297badb1a3320b1da4245fedc71f058885c758a39a49927b309718e9d1668b4f86c
  secret_key_base: 015b885dcefb008d629d2c5f6ceb6cbc2b501ff0627f887be1bd797715fd78991c363d13865f43de7b3d0b1452e2f64b7fae7565783322ad60c4420cd456630e

test:
  secret_key_base: 4d037482838deb82a944eb8cad7189217619ec19f696a7bfcc57d28ee77bd1b23fc3a3a66834803ad398ebcb63aa653688ec8a8ade6008c393ff757b04b8ec94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
